server:
  port: 8000

spring:
  application:
    name: discovery-app

eureka:
  server:
    renewal-percent-threshold: 1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka
