server:
  port: 8000

spring:
  application:
    name: discovery-app

eureka:
  server:
    eviction-interval-timer-in-ms: 0
    renewal-percent-threshold: 1
  client:
    register-with-eureka: false
    fetch-registry: false