server:
  port: 0

spring:
  application:
    name: worker-app

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: ${spring.application.name}-${random.value}

management:
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
