version: "3"
services:
  redis:
    container_name: hashing-redis
    image: redis:5.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
  cassandra:
    container_name: hashing-cassandra
    image: cassandra:3.11.0
    ports:
      - 9042:9042