server:
  port: 8100

spring:
  application:
    name: proxy-app

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

management:
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
