server:
  port: 8100

spring:
  application:
    name: proxy-app

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
